In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### Sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',]

In [3]:
## Define voc size
voc_size = 10000

In [4]:
## One hot representation
one_hot_rep = [one_hot(words, voc_size)for words in sent]
one_hot_rep

[[1545, 6324, 2837, 2052],
 [1545, 6324, 2837, 4459],
 [1545, 8927, 2837, 4069],
 [5756, 9935, 3494, 7709, 5733],
 [5756, 9935, 3494, 7709, 9342],
 [7521, 1545, 4109, 2837, 3086],
 [7745, 3169, 6877, 7709]]

In [5]:
## Word embedding representation
from tensorflow.keras.layers import Embedding, Input
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np


In [7]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep,padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1545 6324 2837 2052]
 [   0    0    0    0 1545 6324 2837 4459]
 [   0    0    0    0 1545 8927 2837 4069]
 [   0    0    0 5756 9935 3494 7709 5733]
 [   0    0    0 5756 9935 3494 7709 9342]
 [   0    0    0 7521 1545 4109 2837 3086]
 [   0    0    0    0 7745 3169 6877 7709]]


In [8]:
## feature representation
dimensions = 10


In [9]:
model=Sequential()
## model.add(Embedding(voc_size,dimensions, input_length=sent_length)) Old Keras 2 Style i.e depricated
model.add(Embedding(voc_size, dimensions, input_shape=(sent_length,))) ## New Keras 3 Style
model.compile('adam','mse') 

e:\ANN\annclassification\venv\Lib\site-packages\keras\src\layers\core\embedding.py:126: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step


array([[[-0.00980091, -0.0154595 ,  0.0111385 , -0.0045838 ,
         -0.01804308,  0.00222268, -0.03798207, -0.00385802,
          0.01928267, -0.01924509],
        [-0.00980091, -0.0154595 ,  0.0111385 , -0.0045838 ,
         -0.01804308,  0.00222268, -0.03798207, -0.00385802,
          0.01928267, -0.01924509],
        [-0.00980091, -0.0154595 ,  0.0111385 , -0.0045838 ,
         -0.01804308,  0.00222268, -0.03798207, -0.00385802,
          0.01928267, -0.01924509],
        [-0.00980091, -0.0154595 ,  0.0111385 , -0.0045838 ,
         -0.01804308,  0.00222268, -0.03798207, -0.00385802,
          0.01928267, -0.01924509],
        [-0.02719181, -0.0154601 , -0.02300124, -0.02810619,
          0.01882824,  0.01989475,  0.02189043,  0.0435678 ,
          0.01562582, -0.04260194],
        [-0.00499324,  0.01979375, -0.04331472,  0.03439688,
          0.03419241, -0.01596296,  0.00686621,  0.04942305,
          0.02868917,  0.01733417],
        [ 0.00282489, -0.02683026, -0.02760036, -0.0

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 1545, 6324, 2837, 2052], dtype=int32)

In [13]:
model.predict(embedded_docs[0].reshape(1,-1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step


array([[[-0.00980091, -0.0154595 ,  0.0111385 , -0.0045838 ,
         -0.01804308,  0.00222268, -0.03798207, -0.00385802,
          0.01928267, -0.01924509],
        [-0.00980091, -0.0154595 ,  0.0111385 , -0.0045838 ,
         -0.01804308,  0.00222268, -0.03798207, -0.00385802,
          0.01928267, -0.01924509],
        [-0.00980091, -0.0154595 ,  0.0111385 , -0.0045838 ,
         -0.01804308,  0.00222268, -0.03798207, -0.00385802,
          0.01928267, -0.01924509],
        [-0.00980091, -0.0154595 ,  0.0111385 , -0.0045838 ,
         -0.01804308,  0.00222268, -0.03798207, -0.00385802,
          0.01928267, -0.01924509],
        [-0.02719181, -0.0154601 , -0.02300124, -0.02810619,
          0.01882824,  0.01989475,  0.02189043,  0.0435678 ,
          0.01562582, -0.04260194],
        [-0.00499324,  0.01979375, -0.04331472,  0.03439688,
          0.03419241, -0.01596296,  0.00686621,  0.04942305,
          0.02868917,  0.01733417],
        [ 0.00282489, -0.02683026, -0.02760036, -0.0