In [31]:
from tensorflow.keras.preprocessing.text import one_hot

In [32]:
### Sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',]

In [33]:
## Define voc size
voc_size = 10000

In [34]:
## One hot representation
one_hot_rep = [one_hot(words, voc_size)for words in sent]
one_hot_rep

[[2378, 4004, 6358, 1065],
 [2378, 4004, 6358, 5147],
 [2378, 4742, 6358, 5901],
 [4092, 5331, 4885, 7881, 738],
 [4092, 5331, 4885, 7881, 2525],
 [285, 2378, 1044, 6358, 135],
 [4906, 8787, 8538, 7881]]

In [35]:
## Word embedding representation
from tensorflow.keras.layers import Embedding, Input
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [36]:
import numpy as np


In [37]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep,padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2378 4004 6358 1065]
 [   0    0    0    0 2378 4004 6358 5147]
 [   0    0    0    0 2378 4742 6358 5901]
 [   0    0    0 4092 5331 4885 7881  738]
 [   0    0    0 4092 5331 4885 7881 2525]
 [   0    0    0  285 2378 1044 6358  135]
 [   0    0    0    0 4906 8787 8538 7881]]


In [38]:
## feature representation
dimensions = 10


In [ ]:
model=Sequential()
## model.add(Embedding(voc_size,dimensions, input_length=sent_length)) Old Keras 2 Style i.e depricated
model.add(Embedding(voc_size, dimensions, input_shape=(sent_length,))) ## New Keras 3 Style
model.compile('adam','mse') 

e:\ANN\annclassification\venv\Lib\site-packages\keras\src\layers\core\embedding.py:126: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [43]:
model.summary()

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [44]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step


array([[[-2.24808455e-02, -2.50447989e-02,  3.49209458e-03,
         -3.79872099e-02,  1.33491643e-02, -3.98473851e-02,
          3.32515873e-02, -3.75613794e-02,  1.87328570e-02,
          1.89389102e-02],
        [-2.24808455e-02, -2.50447989e-02,  3.49209458e-03,
         -3.79872099e-02,  1.33491643e-02, -3.98473851e-02,
          3.32515873e-02, -3.75613794e-02,  1.87328570e-02,
          1.89389102e-02],
        [-2.24808455e-02, -2.50447989e-02,  3.49209458e-03,
         -3.79872099e-02,  1.33491643e-02, -3.98473851e-02,
          3.32515873e-02, -3.75613794e-02,  1.87328570e-02,
          1.89389102e-02],
        [-2.24808455e-02, -2.50447989e-02,  3.49209458e-03,
         -3.79872099e-02,  1.33491643e-02, -3.98473851e-02,
          3.32515873e-02, -3.75613794e-02,  1.87328570e-02,
          1.89389102e-02],
        [ 3.20740677e-02,  1.72176994e-02,  2.75571980e-02,
          4.76424955e-02, -1.03814378e-02,  2.62891091e-02,
          7.56420195e-04,  2.02888288e-02, -2.860767

In [45]:
embedded_docs[0]

array([   0,    0,    0,    0, 2378, 4004, 6358, 1065], dtype=int32)

In [49]:
model.predict(embedded_docs[0].reshape(1,-1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[[-2.24808455e-02, -2.50447989e-02,  3.49209458e-03,
         -3.79872099e-02,  1.33491643e-02, -3.98473851e-02,
          3.32515873e-02, -3.75613794e-02,  1.87328570e-02,
          1.89389102e-02],
        [-2.24808455e-02, -2.50447989e-02,  3.49209458e-03,
         -3.79872099e-02,  1.33491643e-02, -3.98473851e-02,
          3.32515873e-02, -3.75613794e-02,  1.87328570e-02,
          1.89389102e-02],
        [-2.24808455e-02, -2.50447989e-02,  3.49209458e-03,
         -3.79872099e-02,  1.33491643e-02, -3.98473851e-02,
          3.32515873e-02, -3.75613794e-02,  1.87328570e-02,
          1.89389102e-02],
        [-2.24808455e-02, -2.50447989e-02,  3.49209458e-03,
         -3.79872099e-02,  1.33491643e-02, -3.98473851e-02,
          3.32515873e-02, -3.75613794e-02,  1.87328570e-02,
          1.89389102e-02],
        [ 3.20740677e-02,  1.72176994e-02,  2.75571980e-02,
          4.76424955e-02, -1.03814378e-02,  2.62891091e-02,
          7.56420195e-04,  2.02888288e-02, -2.860767